### ISSUE TITLE
Broken With macOS 10.12

### ISSUE THREAD

**Issue by eduncan911** [cmd-johnson/atom-battery-status#12]
I upgraded Atom recently and several plugins required updates (like `go-plus` and others).

Today I noticed I no longer have a battery indicator (cause laptop ran outta juice while in Atom).  

I've uninstalled, restarted Atom, re-installed this plugin - nothing shows up.

I noticed that there is Space inserted into the statusbar when enabling/disabling this plugin.

Lastly, Atom's console shows no messages or info related to this plugin.

If I can help debug further, let me know and I'll try.

**Comment by cmd-johnson** [comment]
I just upgraded Atom to 1.12.8, the indicator works fine for me.
Is the charge percentage being displayed when you tick the 'Show Percentage' option of the plugin?
The other thing you could try is pressing `Ctrl+Shift+I` to bring up the developer tools pane, followed by `Ctrl+Shift+C` and then click on the space in the status bar where you suspect the icon to be. That should highlight the corresponding line in Atom's HTML, which might give us a clue on what's going on here. The following lines (with `class` and `style` attributes depending on the current charging status) should all be present when the plugin intself is working as intended:
![screenshot from 2017-01-04 23-42-22](https://cloud.githubusercontent.com/assets/12250169/21661994/7a5563f8-d2d7-11e6-8549-1c9079923699.png)

If that's the case, the only thing I can come up with right now would be that maybe the icon font I'm using for the icon isn't properly loaded and therefore cannot be displayed, which means there would be more investigation to be done!

**Comment by eduncan911** [comment]
macOS: `CMD-ALT-I` for pane, `CMD-SHIFT-C` to select element.  ;)

> Is the charge percentage being displayed when you tick the 'Show Percentage' option of the plugin?

Nope.  I cannot hover, click, right-click or anything in that "space" that the battery icon goes/shows the space when I enable/disable.

Zero interaction.

> The other thing you could try is pressing Ctrl+Shift+I to bring up the developer tools pane, followed by Ctrl+Shift+C and then click on the space in the status bar where you suspect the icon to be.

I cannot seem to select anything in this area.  Using the selector tool, I can pick anything to the LEFT or RIGHT of this blank space.

<img width="471" alt="screen shot 2017-01-12 at 3 46 09 am" src="https://cloud.githubusercontent.com/assets/104980/21882836/4067c87c-d87a-11e6-9ad9-3b4a7bc8a1eb.png">

<img width="485" alt="screen shot 2017-01-12 at 3 46 21 am" src="https://cloud.githubusercontent.com/assets/104980/21882838/459aad3c-d87a-11e6-87e8-0b179e6b2927.png">

But when hovering exactly where the icon space shows up when enabling/disabling, it doesn't allow me to select anything.  

<img width="478" alt="screen shot 2017-01-12 at 3 46 31 am" src="https://cloud.githubusercontent.com/assets/104980/21882843/4a54f242-d87a-11e6-961e-d98c31c73b09.png">


> I just upgraded Atom to 1.12.8

Argh... Thank you for that.  When I upgraded form 1.12.7 to 1.12.8, I got flooded with deprecated methods.  

Anyhoot, I upgraded to 1.12.8... No dice.

I also uninstalled the plugin, restarted Atom, installed the plugin.  Exact same thing.


> he only thing I can come up with right now would be that maybe the icon font I'm using for the icon isn't properly loaded and therefore cannot be displayed

macOS 10.12.1

Quite possibly.  If it is at all related, I recently installed Go's fonts (which rebuilds all of macOS fonts at the time) around the time I noticed the battery icon stopped working.  But that could have been within a month or so as I haven't been in Atom in a while.

**Comment by cmd-johnson** [comment]
I would've expected that at least the percentage would be shown, since that doesn't specify any font and should therefore display just fine (as long as "Only Show In Fullscreen" isn't ticked or you're in full screen mode)...

Since it appears nothing is being shown at all, the next step would be to determine whether the issue is on the code or the HTML/CSS side of things. If you search for `<battery-status` in the developer pane, does anything come up? That element should be added to the status bar exactly once if the code is doing what it's supposed to do.

If it's not there, maybe check for `styles/battery-status.css`, the stylesheet should automatically get loaded by Atom, regardless of what the code does. If the stylesheet is there, you can check if the icon-font was properly loaded in the developer tools in the Sources tab, at `top -> battery-status -> fonts -> battery-icons.woff`. If it's there, the icon font shouldn't be the problem either.

**Comment by eduncan911** [comment]
Yep, in full screen mode.

> next step would be to determine whether the issue is on the code or the HTML/CSS side of things. If you search for <battery-status in the developer pane, does anything come up? 

Warmer!!!

![image](https://cloud.githubusercontent.com/assets/104980/21944868/642e8c78-d9a6-11e6-81e1-0aa57e830d78.png)

And I checked the "Only show in full screen" option to see if it mattered, which changes to:

![image](https://cloud.githubusercontent.com/assets/104980/21944658/5881eb78-d9a5-11e6-9560-859b06c24a89.png)

As you can see, it is listed.  But, there's nothing there.  

> check for styles/battery-status.css, the stylesheet should automatically get loaded by Atom

Yep, it is:

![image](https://cloud.githubusercontent.com/assets/104980/21944739/b818345c-d9a5-11e6-8795-e2664eabd11a.png)


Didn't go any further since the HTML is blank, which would indicate a coding issue?

macOS 10.12.1

Let me know if I can help debug further.

**Comment by cmd-johnson** [comment]
Interesting...
I got my MacBook running macOS 10.11 from work, Atom was still at 1.11 and the plugin worked flawlessly. Updated the plugin, still worked. Updated Atom to 1.13, still works. Updated OS X to 10.12 and the HTML misses all attributes and contents, except for the root element.

I should be able to take it from here, if I need your help or made any progress, I'll get back to you!

**Comment by cmd-johnson** [comment]
Okay, seems like my node module that is supposed to return the battery information is broken with OS X Sierra, because it relies on the output of `pmset -g batt` and the format seems to have changed between macOS 10.11 and 10.12.
Modifying the source code of `node-power-info` to always return the same value makes the plugin display the stats correctly, indicating that this is in fact not an issue with this package, but only with `node-power-info`.
I opened a bug at the node module and will fix it right away: cmd-johnson/node-power-info#3

**Comment by cmd-johnson** [comment]
Fixed the bug on the other module, reinstalling the plugin should fix the issue for you!
I'll leave this issue open until you confirmed this.

**Comment by eduncan911** [comment]
Confirmed!

Awesome support.  Closing issue now.  👍

**Comment by cmd-johnson** [comment]
You are most welcome. Thank you for bringing this to my attention!
